### ISSUE TITLE
an example of use?

### ISSUE THREAD

**Issue by globsecure** [Calotype/SEO#10]
Hey man,

You would show me an example of use?

**Comment by bryantebeek** [comment]
@globsecure Yea, I should write documentation soon...

Basically you should be using the `generate` method of the `MetaGenerator` and `OpenGraphGenerator` in your templating engine to render the meta and opengraph tags.

Next, for the `MetaGenerator`, you can either make an object `MetaAware` (that's an interface) and use the `MetaGenerator`'s `fromObject` method and pass the `MetaAware` object, or you can use the `setTitle`, `setDescription`, `setKeywords` and `setCanonical` methods.

The `OpenGraphGenerator` takes a `OpenGraphAware` object using, again, the `fromObject` method. 

The `SitemapGenerator` works basically the same.. use `generate` on the `SitemapGenerator` to generate the sitemap, if you use the Laravel service provider, that should be done automatically in the provider, otherwise you'll need to create your own route that generates the sitemap.

Lastly, the `RobotsGenerator`, works just like the sitemap generator, if you are using Laravel the robots.txt should be generated automatically, otherwise generate it yourself. 

What data should be returned from the methods that are part of the contract interfaces is shown in the PHPDoc of those methods in the contracts, so please refer to those for now to learn what you should return when making your objects SEO aware.

If you have any more questions, just ask me and I'll see if I can help ;)
And again, I need to write documentation for this soon, makes all a bit more clear, sorry about that...

**Comment by globsecure** [comment]
Thanks for your response! 
I can use it in the Template? I still do not quite understand where I call the SEO\Meta i read in the code more tests it seems to generate a.
